export const GUARD_AI_CONFIG = {
  patrolSpeed: 1.8,
  investigateSpeed: 2.1,
  returnSpeed: 2.2,
  chaseSpeed: 4.8,
  suspiciousReactionDelay: .28,
  chaseReactionDelay: .18,
  lostSightGrace: .75,
  predictionDistance: .7,
  investigateArrivalRadius: 1.02,
  investigateStallTimeout: .8,
  investigateBlockedArrivalRadius: 1.5,
  returnArrivalRadius: .14,
  returnStallTimeout: .9,
  searchPointArrivalRadius: .28,
  searchPointRadius: 1.55,
  searchPointRadii: [.72, 1.12, 1.55, 1.92],
  searchCandidateDirections: 8,
  searchPointMinSpacing: .52,
  searchStallTimeout: .72,
  searchDuration: 8,
  searchScanDuration: .72,
  searchInspectDelay: 1.05,
  searchPointCount: 3,
  captureDistance: .82,
  alarm: {
    speedMultiplier: 1.15,
    searchDurationMultiplier: 1.3,
    reactionDelayMultiplier: .9,
    searchPointCount: 4,
  },
} as const;
