export const BALANCE = {
  player: {
    walkSpeed: 150,
    runSpeed: 215,
    crouchSpeed: 88,
    minimumVision: 215,
    crouchVisionPenalty: 24,
    crouchDetectionMultiplier: .7,
  },
  noise: {
    walkRadius: 115,
    walkLootBonus: 8,
    walkInterval: .52,
    runRadius: 390,
    runLootBonus: 18,
    runInterval: .27,
    crouchRadius: 65,
    crouchLootBonus: 6,
    crouchInterval: .72,
    wallMultiplier: .58,
    alertMultiplier: .06,
  },
  guard: {
    patrolVision: 390,
    chaseVision: 465,
    patrolVisionAngle: .56,
    chaseVisionAngle: .82,
    darkZoneVisionMultiplier: .85,
    darkZoneVisualRangeMultiplier: .62,
  },
  lighting: {
    playerDarkZoneVisionMultiplier: .78,
    switchCooldown: 4,
    guardInvestigationRadiusOff: 640,
    guardInvestigationRadiusOn: 420,
  },
  cctv: {
    exposureRangeBase: .72,
    exposureRangeWeight: .42,
    detectionBase: .58,
    detectionExposureWeight: .72,
    detectionAlertWeight: .11,
  },
  scoring: {
    lootMultipliers: [0, 1, 1.15, 1.35],
    speedBonusStart: 1200,
    speedPenaltyPerSecond: 7,
    perfectStealthBonus: 1000,
  },
  lockdown: {
    cctvBase: 7,
    cctvPerAlert: 2,
    finalLootBase: 11,
    finalLootPerAlert: 1.5,
  },
} as const;
