export enum GamePhase {
  INFILTRATION = 'INFILTRATION',
  CROWN_STEAL = 'CROWN_STEAL',
  ALARM = 'ALARM',
  LOCKDOWN = 'LOCKDOWN',
  ESCAPE = 'ESCAPE',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
}
